// <auto-generated />
using System;
using ChatApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatApp.Infrastructure.Migrations
{
    [DbContext(typeof(ChatAppDbContext))]
    [Migration("20250531174313_seed variable length user")]
    partial class seedvariablelengthuser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.Domain.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId", "ReceiverId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("ChatApp.Domain.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ChatApp.Domain.Models.TestModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestModel");
                });

            modelBuilder.Entity("ChatApp.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7017),
                            Email = "User-1@gmail.com",
                            FullName = "User 1",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7030),
                            Email = "User-2@gmail.com",
                            FullName = "User 2",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7036),
                            Email = "User-3@gmail.com",
                            FullName = "User 3",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7042),
                            Email = "User-4@gmail.com",
                            FullName = "User 4",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7048),
                            Email = "User-5@gmail.com",
                            FullName = "User 5",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user5"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7056),
                            Email = "User-6@gmail.com",
                            FullName = "User 6",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user6"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7062),
                            Email = "User-7@gmail.com",
                            FullName = "User 7",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user7"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7067),
                            Email = "User-8@gmail.com",
                            FullName = "User 8",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user8"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7073),
                            Email = "User-9@gmail.com",
                            FullName = "User 9",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user9"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7080),
                            Email = "User-10@gmail.com",
                            FullName = "User 10",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7087),
                            Email = "User-11@gmail.com",
                            FullName = "User 11",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user11"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7104),
                            Email = "User-12@gmail.com",
                            FullName = "User 12",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user12"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7110),
                            Email = "User-13@gmail.com",
                            FullName = "User 13",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user13"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7116),
                            Email = "User-14@gmail.com",
                            FullName = "User 14",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user14"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2025, 5, 31, 17, 43, 12, 282, DateTimeKind.Utc).AddTicks(7121),
                            Email = "User-15@gmail.com",
                            FullName = "User 15",
                            HashedPassword = "123456",
                            IsOnline = false,
                            UserName = "user15"
                        });
                });

            modelBuilder.Entity("ChatApp.Domain.Models.Friendship", b =>
                {
                    b.HasOne("ChatApp.Domain.Models.User", "Receiver")
                        .WithMany("FriendRequestsReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatApp.Domain.Models.User", "Sender")
                        .WithMany("FriendRequestsSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ChatApp.Domain.Models.Message", b =>
                {
                    b.HasOne("ChatApp.Domain.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatApp.Domain.Models.Message", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChatApp.Domain.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ChatApp.Domain.Models.User", b =>
                {
                    b.Navigation("FriendRequestsReceived");

                    b.Navigation("FriendRequestsSent");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
